config/routes.rb
BreaksServer::Application.routes.draw do
  resources :messages

  resources :tasks

  resources :maps

  resources :positions

  resources :users

  match 'getTasksByMapID/:id' => 'tasks#getTasksByMapID'
  match 'finishTaskByTaskID/:id' => 'tasks#finishTaskByTaskID'

  match 'positions/createOrUpdatePage/:id' => 'positions#createOrUpdatePage'
  match 'getPositionsByMapID/:id' => 'positions#getPositionsByMapID'
  match 'createOrUpdatePosition' => 'positions#createOrUpdate'

  match 'createOrUpdateUser' => 'users#createOrUpdate'

  match 'users/createOrUpdatePage/:id' => 'users#createOrUpdatePage'

  match 'users/getUser/:id' => 'users#getUserByPhoneID'

end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :map_id, :user_id, :x, :y

  belongs_to :user
  belongs_to :map
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  protect_from_forgery :except => [:createOrUpdate, :getPositionsByMapID]
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
      format.xml { render xml: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
      format.xml { render xml: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
      format.xml { render xml: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  def createOrUpdatePage
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # createOrUpdatePage.html.erb
      format.json { render json: @position }
      format.xml { render xml: @position }
    end
  end

  # POST /createOrUpdate
  # POST /createOrUpdate.xml
  # POST /createOrUpdate.json
  def createOrUpdate
    user = User.find_by_phoneID params[:phoneID]
    pos = Position.where("user_id = ? AND map_id = ?", user.id, params[:mapID])

    if pos != nil and pos[0] != nil
      puts pos[0]
      pos = pos[0]
      respond_to do |format|
        if pos.update_attributes(:x => params[:x], :y => params[:y])
          format.html { redirect_to pos, notice: 'position was successfully updated.' }
          format.json { render json: pos}
          format.xml { render xml: pos}
        else
          format.html { render action: "new" }
          format.json { render json: pos.errors, status: :unprocessable_entity }
          format.xml { render xml: pos.errors, status: :unprocessable_entity }
        end
      end
    else
      pos = Position.create(user_id: user.id, map_id: params[:mapID], x: params[:x], y: params[:y])
      respond_to do |format|
        if pos.save
          format.html { redirect_to pos, notice: 'User was successfully created.' }
          format.json { render json: pos, status: :created, location: pos }
          format.xml { render xml: pos, status: :created, location: pos }
        else
          format.html { render action: "new" }
          format.json { render json: pos.errors, status: :unprocessable_entity }
          format.xml { render xml: pos.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def getPositionsByMapID
    @positions = Position.where('map_id = ?', params[:id])

    respond_to do |format|
      format.xml  { render xml: @positions.to_xml(:include => :user) }
    end
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
        format.xml { render xml: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
        format.xml { render xml: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
        format.xml { render xml: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :map_id %><br />
    <%= f.text_field :map_id %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/createOrUpdatePage.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@position, :url => "/createOrUpdatePosition.xml") do |f| %>
    <% if @position.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

          <ul>
            <% @position.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <label for="phoneID">phoneID</label><br />
      <input id="phoneID" name="phoneID" size="30" type="text" value="1">
    </div>
    <div class="field">
      <label for="mapID">mapID</label><br />
      <input id="mapID" name="mapID" size="30" type="text" value="1">
    </div>
    <div class="field">
      <label for="x">x</label><br />
      <input id="x" name="x" size="30" type="text" value="1">
    </div>
    <div class="field">
      <label for="y">y</label><br />
      <input id="y" name="y" size="30" type="text" value="1">
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Map</th>
    <th>X</th>
    <th>Y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.user_id %></td>
    <td><%= position.map_id %></td>
    <td><%= position.x %></td>
    <td><%= position.y %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @position.user_id %>
</p>

<p>
  <b>Map:</b>
  <%= @position.map_id %>
</p>

<p>
  <b>X:</b>
  <%= @position.x %>
</p>

<p>
  <b>Y:</b>
  <%= @position.y %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>